name: fitness
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.6.0
  flutter_svg: ^1.1.6
  flutter_native_splash: ^2.2.14

flutter_native_splash:
  color: "#896BFF"
  image: assets/images/im_logo.png

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - fonts/

  fonts:
    - family: Urbanist
      fonts:
        - asset: fonts/Urbanist-Bold.ttf
          weight: 700
        - asset: fonts/Urbanist-Semibold.ttf
          weight: 600
        - asset: fonts/Urbanist-Medium.ttf
          weight: 500
        - asset: fonts/Urbanist-Regular.ttf
          weight: 400
